name : Check sorts
on:
  push:
    branches:
      - master
  pull_request:
    branches: 
      - master
jobs:
   checker:
      runs-on: ubuntu-latest
      steps:
        - name: Sorting algorithms checker
          timeout-minutes: 1
          run: |
            apt-get cmake
            mkdir build && cd build
            cmake ..
            cmake --build .
            ./main
            
