name: Check sorts
on:
  push:
   branches:
     - main
  pull_request:
    branches: 
      - main
  workflow_dispatch:

jobs:
  checker:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and run tests
        run: |
          sudo apt install -y libtbb-dev
          chmod +x run.sh && ./run.sh
