name: Check sorts
on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

jobs:
  checker:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          set -e
          sudo apt-get update
          sudo apt-get install -y cmake

      - name: Build and run tests
        run: |
          set -e
          mkdir build && cd build
          cmake ..
          cmake --build .
          ./main
